spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/mall?characterEncoding=UTF-8&serverTimezone=GMT%2b8:00
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
server:
  port: 9508
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
